import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--noto-sans",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--roboto-mono",
});

export const metadata: Metadata = {
  title: "Amser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${notoSansJP.variable} ${robotoMono.variable} bg-background`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
